<#
.SYNOPSIS
    Creates a ServiceNow incident for an Intune resource expiry event.

.DESCRIPTION
    Calls the ServiceNow Table API to create an incident when a monitored resource
    reaches URGENT health state (or CRITICAL, depending on configuration).

    Priority mapping:
        URGENT   → Priority 1 (Critical)
        CRITICAL → Priority 2 (High)
        WARNING  → Priority 3 (Moderate)

.PARAMETER EvaluationResult
    The PSCustomObject output from Invoke-ThresholdEvaluation.ps1.

.PARAMETER Config
    The full monitoring configuration object from monitoring_config.json.

.NOTES
    Phase 9 feature. Set enableServiceNow: true in monitoring_config.json to activate.
    Requires a ServiceNow instance with REST API access.
#>

function Send-ServiceNowAlert {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [ValidateNotNull()]
        [PSCustomObject]$EvaluationResult,

        [Parameter(Mandatory = $true)]
        [ValidateNotNull()]
        [PSCustomObject]$Config
    )

    $ResourceName   = $EvaluationResult.DisplayName
    $HealthState    = $EvaluationResult.HealthState
    $DaysRemaining  = $EvaluationResult.DaysRemaining
    $ExpirationDate = if ($EvaluationResult.ExpirationDate) { $EvaluationResult.ExpirationDate.ToString("dd MMMM yyyy") } else { "Unknown" }

    # Priority mapping
    $Priority = switch ($HealthState) {
        "URGENT"   { $Config.alerting.serviceNow.urgentPriority   }
        "CRITICAL" { $Config.alerting.serviceNow.criticalPriority  }
        "WARNING"  { $Config.alerting.serviceNow.warningPriority   }
        default    { 3 }
    }

    Write-Verbose "[Alert:ServiceNow] Creating incident for [$HealthState] $ResourceName"

    $InstanceUrl       = $Config.alerting.serviceNow.instanceUrl
    $TableApiUrl       = "$InstanceUrl/api/now/table/incident"
    $AssignmentGroup   = $Config.alerting.serviceNow.defaultAssignmentGroup

    $ShortDescription  = "[$HealthState] Intune Expiry Alert: $ResourceName — $DaysRemaining days remaining"
    $Description       = @"
Microsoft Intune Expiry Monitoring Platform — Automated Incident

Resource     : $ResourceName
Health State : $HealthState
Days Remaining: $DaysRemaining days
Expires On   : $ExpirationDate
Description  : $($EvaluationResult.Description)

This incident was automatically generated by the Intune Expiry Monitoring Platform.
Expiration Date: $ExpirationDate
"@

    $IncidentBody = @{
        short_description = $ShortDescription
        description       = $Description
        priority          = [string]$Priority
        assignment_group  = $AssignmentGroup
        category          = "Infrastructure"
        subcategory       = "Certificate Management"
    }

    $Credentials = [System.Convert]::ToBase64String(
        [System.Text.Encoding]::ASCII.GetBytes("$($Config.alerting.serviceNow.apiUser):$($Config.alerting.serviceNow.apiPassword)")
    )

    $Headers = @{
        "Authorization" = "Basic $Credentials"
        "Content-Type"  = "application/json"
        "Accept"        = "application/json"
    }

    try {
        $Response = Invoke-RestMethod `
            -Uri     $TableApiUrl `
            -Method  POST `
            -Headers $Headers `
            -Body    ($IncidentBody | ConvertTo-Json) `
            -ErrorAction Stop

        $IncidentNumber = $Response.result.number
        Write-Host "  ✓ [Alert:ServiceNow] Incident created: $IncidentNumber" -ForegroundColor Green
    }
    catch {
        Write-Error "[Alert:ServiceNow] Failed to create ServiceNow incident: $($_.Exception.Message)"
    }
}
